manyminds/api2go

- api.go
> include http.Header in apig2o.Request #57

- marshal.go
- marshal_test.go
> Bugfix slices

- api.go
> bugfix build correct request object in handleLinked

- api.go
- api_test.go
This commit does not allow arrays in update anymore
> Modify update to work with patch as per rc3 spec

- README.md
- examples/crud_example.go
Very small update to the README and example comments to specify using `PATCH` instead of `PUT`. Everything else was great to get up and running :smile_cat:
> update readme, example to use PATCH instead of PUT

- README.md
This was really necessary! The README should now be up to date with our latest features and easier to understand.
Please read all of it very carefully to find all mistakes! It's very important to have good documentation.
> update and restructure the README.md

- README.md
- examples/crud_example.go
- jsonapi/fixtures_test.go
- jsonapi/helpers.go
- jsonapi/helpers_test.go
- jsonapi/marshal.go
- jsonapi/marshal_test.go
- jsonapi/unmarshal.go
- jsonapi/unmarshal_test.go
> Rename struct fields 

- api.go
- api_test.go
- examples/crud_example.go
- jsonapi/unmarshal.go
This is a proposal to support pointer resources in addition to non-pointer resources. That is, adding support for this:
```go
api.AddResource(&Post{}, &PostsSource{})
```
The use case is being able to easily link resources so that a change to a linked resource is reflected when retrieving the representation of a resource that links to it.
Currently, the following behavior of the pretty simple CRUD example is very surprising (and probably unintended):
```json
$ curl -X POST http://localhost:31415/v0/chocolates -d '{"data" : [{"type" : "chocolates" , "name" : "Ritter Sport", "taste": "Very Good"}]}'
{
"data": {
"id": "1",
"name": "Ritter Sport",
"taste": "Very Good",
"type": "chocolates"
}
}
$ curl -X POST http://localhost:31415/v0/users -d '{"data" : [{"type" : "users" , "user-name" : …
```
> Add support for pointer resources

- README.md
- api.go
- api_test.go
- jsonapi/integration_test.go
- jsonapi/marshal.go
- jsonapi/marshal_test.go
- jsonapi/unmarshal.go
- jsonapi/unmarshal_test.go
> relationships for 1.0

- README.md
- api.go
- api_test.go
- examples/crud_example.go
This resolves #125 
Thanks a lot again to @tanmayambre for finding the bug!
A new test for this will be added before this get's merged @sharpner works on it :)
> Route bugfix

- api.go
- examples/crud_example.go
- examples/crud_example_test.go
- examples/examples_suite_test.go
- examples/model/model_chocolate.go
- examples/model/model_user.go
- examples/resource/resource_chocolate.go
- examples/resource/resource_user.go
- examples/storage/storage_chocolate.go
- examples/storage/storage_user.go
The example is now way better! It's split up into separate files and it has it's own integration test suite.
I also found a bug related to updating relationships which is now fixed and covered by an integration test in the example project.
This resolves #131
> Improve example

- .travis.yml
- README.md
- examples/crud_example.go
- jsonapi/fixtures_test.go
- jsonapi/marshal_test.go
- jsonapi/unmarshal_test.go
- scripts/fmtpolice
strict check of gofmt and golint and some nice coverage
> Format police coverage

- api_interfaces_test.go
- jsonapi/unmarshal.go
> Fix renaming bug that ocured while unmarshaling

- api_test.go
- error.go
- jsonapi/integration_test.go
- jsonapi/marshal_same_type_test.go
- jsonapi/marshal_test.go
- jsonapi/unmarshal_test.go
- scripts/fmtpolice
This fixes some minor gofmt issues
> simplify switch for gofmt

- jsonapi/marshal_enum_test.go
- jsonapi/unmarshal.go
> Bugfix unmarshaler interface

- api.go
- api_public.go
- api_test.go
- context.go
- context_test.go
* added net/context as part of API info
* passed this ctx along to handlers
* inserted ctx as part of the Request, backwards compatible.
* very minor update to example that shows you can provide a ctx
closes #169
> Added net/context support.

- jsonapi/fixtures_test.go
- jsonapi/marshal.go
- jsonapi/marshal_test.go
- jsonapi/unmarshal_test.go
This is a second approach to solve the problem, that a time value can be optional.
See: https://github.com/manyminds/api2go/pull/191 and https://github.com/manyminds/api2go/issues/190
> Marshal an empty datetime to zero time.

- jsonapi/marshal.go
- jsonapi/marshal_composition_test.go
- jsonapi/unmarshal.go
> marshaling support for embedded structs

- jsonapi/fixtures_test.go
- jsonapi/unmarshal.go
- jsonapi/unmarshal_test.go
> add missing return

- jsonapi/fixtures_test.go
- jsonapi/marshal_test.go
- jsonapi/unmarshal_test.go
These removed some confusion for me and made it more obvious the zero value and nil relationships.
> Null tests

- jsonapi/fixtures_test.go
- jsonapi/unmarshal_test.go
just a quick test to resolve #204
> test to check if unmarshaling arrays works too

- api_test.go
- jsonapi/marshal.go
- jsonapi/marshal_test.go
> nil Marshals into json object with null

- api.go
- api_test.go
> Fix double forward slash if no prefix was set

- api.go
- api_test.go
- jsonapi/fixtures_test.go
- jsonapi/marshal_test.go
- jsonapi/unmarshal.go
- jsonapi/unmarshal_test.go
and also return correct 406 status code if the type is missing in PATCH and POST requests.
This fixes #234 
Please review @tanmayambre and give some feedback if we need more fixes.
> make attributes optional

- jsonapi/fixtures_test.go
- jsonapi/marshal.go
- jsonapi/marshal_test.go
This is for https://github.com/manyminds/api2go/issues/250
> add ability to override default plural check

- api.go
- jsonapi/benchmark_test.go
- jsonapi/data_structs.go
- jsonapi/data_structs_test.go
- jsonapi/entity_namer.go
- jsonapi/fixtures_test.go
- jsonapi/helpers.go
- jsonapi/integration_test.go
- jsonapi/marshal.go
- jsonapi/marshal_composition_test.go
- jsonapi/marshal_different_to_many_test.go
- jsonapi/marshal_enum_test.go
- jsonapi/marshal_same_type_test.go
- jsonapi/marshal_test.go
- jsonapi/unmarshal.go
- jsonapi/unmarshal_test.go
To get started with #260 I made myself a little more familiar with the internals of this package and came up with some small improvements.
I would also like to rewrite some of the functions documentations and optimize the code a little more. Would that be ok for you?
> Some improvements

- .travis.yml
- README.md
- api_test.go
- context.go
> Use context package from go 1.7

- jsonapi/data_structs.go
- jsonapi/data_structs_test.go
- jsonapi/fixtures_test.go
- jsonapi/marshal.go
- jsonapi/marshal_test.go
> Custom meta in relation

- api.go
- api_test.go
> Return conflict error for incorrect id in PATCH

- .travis.yml
- README.md
- echo_router_test.go
- gingonic_router_test.go
- gorillamux_router_test.go
- httprouter_test.go
- routing/echo.go
- routing/echo_test.go
- routing/gingonic.go
- routing/gorillamux.go
- routing/gorillamux_test.go
This resolves #280 
We really have to do the #301 next
> New adapter for the echo framework

- jsonapi/unmarshal.go
maybe we should add a test though :P
> Fix I saw a few times already

- .travis.yml
> Fix linting import
