- unmarshal.go
- unmarshal_test.go
there was a bug that unmarshalling of json numbers only worked with
float64. api2go now checks if the struct type is a int or uint type and
casts the number to that type.
> unmarshall number into correct int types

- README.md
- api.go
- api_test.go
- helpers.go
- marshal.go
- marshal_test.go
- unmarshal.go
- unmarshal_test.go
The latest specs for [json api](http://jsonapi.org/format/) state:
* Primary data MUST appear under a top-level key named "data".
* Error objects MUST appear under a top-level key named "errors".
* Linkage MUST be expressed as:
* type and id members for to-one relationships. type is not required if the value of id is null.
* type and ids members for homogeneous to-many relationships. type is not required if the value of ids is an empty array ([]).
* A data member whose value is an array of objects each containing type and id members for heterogeneous to-many relationships.
> latest specs from jsonapi.org

- README.md
- api.go
- api_test.go
- marshal.go
- marshal_test.go
This PR introduces the possibility to not specify any related IDs at all and just let a link be auto generated for the client to load related data. See http://jsonapi.org/format/#document-structure-resource-relationships
This introduces the `resource` member in the links object. The resource URL get's automatically generated by Marshalling a struct manually and via the API. For manually marshalling, I introduced 2 more methods to specify a API Prefix. This is now needed because before this feature, the serialisation had nothing to do with URLs. 
So, a new GET Route get's created for referenced structs now like `/v1/posts/1/comments`. If a client requests this URL, the request get's routed to the `FindAll` method of the Resource for `comments` with a Query parameter `PostsID` which in this …
> Resource links

- api.go
- api_test.go
The default behaviour of api2go will be
307 on routes with trailing / but this feature can be
disabled
This provides the functionality wanted in #72
> Introduce method to disable automatic redirects

- README.md
- api.go
- api_test.go
- examples/crud_example.go
- jsonapi/integration_test.go
- jsonapi/marshal.go
- jsonapi/marshal_test.go
- jsonapi/unmarshal.go
- jsonapi/unmarshal_test.go
this resolves #81 and #71 
I looked over jsonapi specs again and did not find any more fields that we have to rename. Apart from renaming we have to continue implementing the other features from the RC3 tickets.
> Rename fields rc3

- api.go
- api_test.go
This fixes #83 
I did a small refactoring for handleLinked. Now the URLs for the router are all pre-generated with all possible relationships. This was necessary. Otherwise there was a conflict because of a previous dynamic segment. But apart form that, it is better that way. 
The new Route to load relations is still a single route with a dynamic segment that is the name of the relation. It would also be possible to pre-register a bunch of routes for that too.
The relationship routes are now "for-free". The FindOne resource methods are used for that too
> new Route to fetch relations

- jsonapi/fixtures_test.go
- jsonapi/marshal_test.go
- jsonapi/unmarshal.go
- jsonapi/unmarshal_test.go
this fixes #103 
the panic is recovered and a proper error will be returned if an incoming field cannot be unmarshalled because it has a wrong type.
> recover from unmarshalling invalid types into fields

- README.md
- api.go
- api_test.go
- examples/crud_example.go
- jsonapi/fixtures_test.go
- jsonapi/integration_test.go
- jsonapi/unmarshal.go
This implements #80.
The huge brainfuck in this code is again reflections and interfaces. Very often a stupid trick is used to get an addressable value of an `interface{}` by using a slice. Because with a slice it is possible to get a pointer to an `interface{}` type via reflection...
But the feature works
Todos:
> Relationship manipulation

- api.go
The idea came up in #106. You can now choose to get a Standard go
Handler or the underlying router instance to further customize api2go
with more routes.
This resolves #106
> Method to get instance of julienschmidt httprouter

- README.md
- jsonapi/fixtures_test.go
- jsonapi/marshal_test.go
- jsonapi/unmarshal.go
- jsonapi/unmarshal_test.go
This fixes #109 
However I am not very happy with the current unmarshaling in api2go. For new types it is required to implement some interfaces in order for them to be marshalled/unmarshaled:
- json.Marshaler
- json.Unmarshaler
Marshalling is done right in api2go and the implemented interface will be used. Unmarshaling however cannot currently use implemented Unmarshaler interfaces.
I would suggest that we open another issue for this matter and refactor our unmarshaling.
But SQL-Types work for now. Once we refactored unmarshaling, any custom type that implements the interfaces can be used, that will be very cool :)
> Sql null types

- jsonapi/unmarshal.go
- jsonapi/unmarshal_test.go
Unmarshaling now works with a single struct as well. We used a slice before because in a previous specification it was possible to send multiple objects to the server. 
However, we will clean up the marshalling in ticket #111 
This resolves ticket #113 and also keeps in mind #112. From a clients perspective it would still be required to unmarshal into a slice because a server can send multiple objects inside a json. 
For now both is supported. If there are multiple objects in a json and the target is a struct, the first entry will be unmarshalled into it, and the rest is ignored. After #111 we should check that too and output an error.
> Unmarshal now supports a struct instead of only slice

- .travis.yml
- api.go
- api_test.go
- examples/crud_example.go
- jsonapi/fixtures_test.go
- jsonapi/integration_test.go
- jsonapi/marshal.go
- jsonapi/marshal_test.go
- jsonapi/unmarshal.go
- jsonapi/unmarshal_test.go
This is a necessary change for v 1.0
All struct payload now is in an `attributes` sub-object inside the `data` object of the json.
This resolves #118
> attributes object in data object

- api.go
- api_test.go
This fixes #127 
A user now has to check in a resources `Create` method whether he can accept the ID that a client send or not.
> allow client generated IDs #127

- jsonapi/marshal.go
- jsonapi/marshal_same_type_test.go
because of a wrong sorting after "type" in marshal.go so me references were
skipped and not correctly marshalled. The unique key that must be used is the
name, not the type because it is possible to have multiple references of the
same type, but with a different name.
> fix a bug with multiple relationships of the same type

- README.md
- api.go
- api_entity_name_test.go
- jsonapi/entity_namer.go
- jsonapi/fixtures_test.go
- jsonapi/marshal.go
- jsonapi/marshal_test.go
- jsonapi/unmarshal.go
the current situation always generated the structs name from it's type. So
a UnicornPost struct would have the generated name `unicornPosts`. But maybe,
a user wants to use a different naming scheme, like `unicorn-posts`. This is
now possible.
Maybe we should change the Jsonify and Dejsonify methods in the future that
they automatically generate *hyphenized* names of everything.
This resolves #134
> new feature to rename a struct

- api_test.go
- error.go
- error_test.go
The Href and Path fields have been removed. The Links, Source and Meta fields have been added.
To update existing code the Href should be changed to
Links: api2go.ErrorLinks{About: "Href Value"},
the Path should be changed to
Source: api2go.ErrorSource{Pointer: "Path Value"},
Refs #137 
`go test` is currently passing.
> Update api2go.Error structure to json api 1.0 spec

- .travis.yml
Since we do not use slack anymore we could change notifications to our
public gitter chat.
> Replace slack notifications with gitter.

- jsonapi/fixtures_test.go
- jsonapi/marshal.go
- jsonapi/marshal_test.go
This is useful if a user only wants to include the `links` without `data`.
Sometimes loading relationships is a very expensive operation. If relations
are not needed anyway, it is enough to send the links. A client can then
access the relations at a later time via the provided links.
This resolves #141
> Skip the `data` field for relations

- api.go
- api_test.go
Fixes #143 
This commit introduces our custom method not allowed handler
currently its private, since there is no need to replace it from
the outside.
TODO:
> add return object to method not allowed error.

- README.md
- api.go
- api_interfaces.go
- api_test.go
- error.go
- error_test.go
- examples/crud_example.go
fixes #117.
The MarshalError method is now public api of the ContentMarshaler interface. It only makes sense here since its necessary to implement different behaviour when using another encoding e.g. cbor.
This PR is a breaking change if someone has already implemented custom content marshalers.
> Introduce public MarshalError for content type.

- api.go
When the API call the findAll method it can be useful to know the Reference Name. If you have a single model with multiple property linked to the same reference type (per ex. a model People, can be linked as Director and Producer in a Film).
> Add a QueryParam with the Name of the Reference

- README.md
- api.go
- api_entity_name_test.go
- api_interfaces.go
- api_interfaces_test.go
- api_test.go
- examples/crud_example_test.go
- examples/resource/resource_chocolate.go
- examples/resource/resource_user.go
- examples/resource/response.go
Create, Update and Delete methods now support an additional return code. In
case of an error, the error return type with a 400 or 500 return code must be
used. In case of success, the int return code can be used.
Whenever an updated response must be sent, the FindOne method is automatically called by the API. 
There is one thing where I do not know how to solve it best, it's the 200 OK Status for Delete. It should be possible to only return some meta data here. Any suggestions?
Resolves #138 
Resolves #86 
Todo:
> Add return code to Resource interface

- jsonapi/fixtures_test.go
- jsonapi/unmarshal.go
- jsonapi/unmarshal_test.go
we did not test it with real json data. The problem was that our current unmarshal implementation always get's an `[]interface{}` and not the desired target type. Until we have a better unmarshaling, this is a fix for that.
> fix slice unmarshal

- README.md
- api_entity_name_test.go
- api_interfaces_test.go
- api_test.go
- examples/crud_example_test.go
- examples/model/model_chocolate.go
- examples/model/model_user.go
- jsonapi/fixtures_test.go
- jsonapi/integration_test.go
- jsonapi/marshal.go
- jsonapi/marshal_enum_test.go
- jsonapi/marshal_same_type_test.go
- jsonapi/unmarshal.go
- jsonapi/unmarshal_test.go
also fixed a model in the examples project which forgot to ignore the ID
field. Tests were wrong too and expected an id field inside attributes.
> use `jsonapi:"-"` tag to ignore fields, fixes #171

- api_public.go
- api_test.go
This can be useful for very basic applications that don't require a special `api2go.Responder` implementation
> api2go.Response as default for api2go.Responder

- README.md
write some documentation about middleware/context usage. So a user that lands on our main page directly sees that this is possible. This resolves #174
> document middleware/context usage

- README.md
- api.go
- api_interfaces.go
- api_public.go
- api_test.go
- examples/crud_example.go
- examples/resolver/resolver.go
- jsonapi/marshal.go
- resolver.go
- resolver_test.go
this commit allows per request dynamic handling of baseUrls
it also deprecates the old NewAPIWithMarshalers in favor
of the new NewAPIWithMarshalling (name is subject to change).
It is fully backwards compatible.
> [WIP] Two new interfaces for baseurl resolving

- README.md
- api.go
- api_interfaces.go
- api_public.go
- content_marshaler.go
- error.go
- examples/resource/resource_user.go
- request.go
- resolver.go
- response.go
- routing/httprouter.go
- routing/router.go
this is particulary useful since more and more people
are trying to use api2go with gin router.
Since we have built so many new features I will restructure our constructors within this pr.
This will probably deprecate every constructor so far except the simple `NewAPI(namespace string)` one.
> [RFC] Extract router to be an interface

- README.md
we still mentioned the old `json:"-"` tag in the documentation
> Improve documentation and fixed ignore tag

- README.md
- api_interfaces.go
this resolves #193 
I also noticed that I switched the update documentation with delete. This is fixed now. We can still decide in the future to move more documentation to godoc and shorten our Readme even more, which is the preferred way for me because a user can stay in the IDE of choice and read all important documentation in there.
> update documentation for CRUD operations

- README.md
this provides better information that we have a `HTTPError` struct that can be used as `error` return value. See #195
> update readme with HTTPError info

- jsonapi/fixtures_test.go
- jsonapi/unmarshal.go
the search needs to go on if the field from the json was not found in the embedded struct and there are other fields. Now there is a check for that.
I changed the struct for the test, that triggered the error too. So we got that covered now.
This resolves #199
> fix too early return when unmarshal embedded structs

- jsonapi/fixtures_test.go
- jsonapi/unmarshal.go
- jsonapi/unmarshal_test.go
The only way to check this that I could find was to use
recover.
If anyone has an idea how to check if a field is private beforehand I would
appreciate it deeply. :/
> Cleaner error message by renamed unexported fields

- api.go
- api_test.go
if the appropriate query parameters are available. The api goes through all
the attributes and only includes the ones from the query parameter. For
example: `?fields[posts]=title,content`
This is pretty ugly because of our internal data structure, that hopefully will be better sometime, see #202
It's already working but I now noticed I forgot to implement it for slices of data when a `FindAll` query get's called for example. 
TODO:
This will resolve #183
> sparse fieldsets filtering support

- api.go
- api_test.go
- jsonapi/unmarshal.go
- jsonapi/unmarshal_test.go
Below is the output of running this integration test and accompanying debug output. This PR demonstrates how in api.go's handleUpdate function the context (ctx) is unmarshaled using encoding/json and correctly contains the attribute named value being set to null. See the Context: below where value:interface{}(nil) is correct. But then after going through jsonapi.UnmarshalInto the nil value has been dropped and the test fails because the attribute was not updated.
```
Context: map[string]interface {}{"data":map[string]interface {}{"type":"posts", "id":"1", "attributes":map[string]interface {}{"title":"New Title", "value":interface {}(nil)}}}
Updated Obj: &{1 New Title {{2 true}} 0xc8205897e0 [{1 This is a stupid post!}] []}
------------------------------
• Failure [0.003 seconds] …
```
> Show UnmarshalInto dropping attributes set to null.

- jsonapi/marshal.go
- jsonapi/marshal_different_to_many_test.go
when marshalling a toMany relationship with the same name but with different types in it, it was previously not possible to set the type for every referenced ID because it was assumed that it would always be of the same type. This is now possible.
Fixes #218
> always take the type our of the ReferenceID struct

- README.md
we should hint v1 instead of v0 so that new users use the new codebase
> Update readme to direct new users to v1

- README.md
This change is the same as in https://github.com/manyminds/api2go-adapter/pull/4/files
> Remove content marshalers from the api2go with gin example

- api.go
- api_interfaces.go
- api_object_initializer_test.go
Hi there!
First of all thanks for this amazing library!
I'm working on a small very opinionated framework that uses struct tags to simplify the declaration of models. I first thought this might get very complicated with `api2go` as it uses `reflect` to create new objects internally. But in fact I learned that most actions go either through `crud.Find()` or `crud.FindAll()` which allows to setup the object before `jsonapi.Marshal()` or `jsonapi.Unmarshal()` is called. The situation that does not allow such access is on a PATCH request. An object gets created with `reflect` right before passing it to `jsonapi.Unmarshal()`.
TL;DR:
This pull request adds an optional method that can be implemented to get access to the dynamically created object in a PATCH request before `jsonapi.Unmarshal()` …
> Added InitializeObject hook

- jsonapi/fixtures_test.go
- jsonapi/marshal.go
- jsonapi/marshal_test.go
Single resource may have duplicates in `included` section when we fetch some deeper relations like in [spec](http://jsonapi.org/format/#fetching-includes)
For example we have post with 2 comments from same author and this request returns duplicated author for each comment:
```
Get /posts/1?include=comments.author
```
> FIX: replace getIncludedStructs(2) by filterDuplicates(2) method call

- examples/crud_example_test.go
- examples/model/model_user.go
When requesting the users, the iteration was over models and not only the reference IDs which caused a bug that no references were in the response JSON when creating a user with some initial sweets.
#270
> Example: Create user with chocolate relationship

- api.go
- jsonapi/data_structs.go
- jsonapi/data_structs_test.go
- jsonapi/fixtures_test.go
- jsonapi/marshal.go
- jsonapi/marshal_test.go
If this is merged, structs may implement methods like the following:
```go
func (s MyStruct) GetCustomLinks(base string) jsonapi.CustomLinks {
return jsonapi.CustomLinks{
"firstlink": jsonapi.CustomLink{Href: base + `/firstlink`},
"secondlink": jsonapi.CustomLink{
Href: base + `/secondlink`,
Meta: map[string]interface{}{"method": "GET"},
},
}
}
```
The [`"links"` object documentation](http://jsonapi.org/format/#document-links) does not specify whether or not custom links are allowed, only that additional standard links may be added in the future. However, custom links are useful for discoverability of additional services the resource may provide, when behavior extends beyond basic CRUD.
Notes:
* As the `"links"` object is not currently used when marshaling the data payload elements (only …
> Allow elements to implement custom links

- api.go
- api_interfaces.go
- api_test.go
- request.go
- response.go
First, adds a `Pagination` map to `api2go.Request` that extracts any pagination query parameters. E.g. `?page[test]=stuff` would contain `{"test": "stuff"}`.
Next, it removes the error if pagination fields are given and `PaginatedFindAll` is not implemented. Instead, it calls `FindAll` as normal. This allows the "supported" pagination params (page/size/offset/limit) to be used with custom pagination logic.
Finally, it adds a `Pagination` struct to `api2go.Response` that can control the pagination links returned by the regular `FindAll` method. This allows `FindAll` to return something like this:
```golang
return &api2go.Response{
// ...,
Pagination: api2go.Pagination{
Next: map[string]string{"cursor": "nextpage"},  // ...?page[cursor]=nextpage
Prev: map[string]string{"cursor": …
```
> Support for custom pagination logic

- README.md
- api.go
- api_interfaces.go
- api_interfaces_test.go
- api_public.go
- api_test.go
Here is a first attempt to split the CRUD interface as mentioned in issue #267.
I really don't like typing the source with an empty interface but as the idea here is to be able to pass one implement of at least one of the new four interfaces, I can't see any other way to make it work.
Suprisingly, tests are passing seamlessly. I probably say surprisingly because I come from a inheritance-based language and composition in Go allows us to make smooth updates on interfaces (❤️). By the way, we do need to test the generated routes by passing several combinations of implementations of these CRUD interfaces.
Let me know what do you think about that !
> Split CRUD interface

- jsonapi/data_structs.go
- jsonapi/fixtures_test.go
- jsonapi/marshal.go
- jsonapi/marshal_test.go
This adds custom meta support for relations:
```
"relationships": {
"author": {
"links": {
"self": "http://my.domain/v1/posts/someID/relationships/author",
"related": "http://my.domain/v1/posts/someID/author"
},
"meta": {
"someMetaKey": "someMetaValue",
"someOtherMetaKey": "someOtherMetaValue"
}
}
}
```
To use this feature, a type has to implement `MarshalCustomRelationshipMeta` and return the meta structure for the type's relations from `GetCustomMeta()`:
```
type MarshalCustomRelationshipMeta interface {
MarshalIdentifier
GetCustomMeta(string) Metas
}
```
A test is included.
> Added support for custom meta info in relations.

- .travis.yml
- api_public.go
- api_test.go
Make it easy to add another version of an API to the routing of the first. This is fixing #290
> Add easy way to combine multiple API versions

- jsonapi/fixtures_test.go
- jsonapi/marshal.go
- jsonapi/marshal_test.go
The included structs of already included structs were not checked and marshalled as well.
We are now checking that recursively. Extended the test so that comments can have sub comments and tested it with a slice of posts and single post which were the 2 entry points that are now both calling the recursive include function. 
This fixes #294
> Recursively marshal included structs

- .travis.yml
Echo dropped the support for go 1.7 which leads us
to either drop support for echo, or go 1.7. :/
That's also why https://github.com/manyminds/api2go/pull/313 fails.
> Drop support for go 1.7 because of echo

- jsonapi/data_structs.go
- jsonapi/data_structs_test.go
- jsonapi/fixtures_test.go
- jsonapi/marshal_test.go
I have an API which returns pagination links (`prev`, `next`, etc.) with null values if there is no previous or next page. I am using this library to write a Go client for it and noticed I started getting `expected a JSON encoded string or object` errors. At first I thought our API was wrong, but after a quick check of the spec, it turns out this actually is something JSONAPI-compliant clients should support.
On first read, the spec seems to contradict itself a bit. Here is bit from the [links element](http://jsonapi.org/format/#document-links), which states:
> The value of each links member MUST be an object (a “links object”).
And here is a quote from the [pagination section](http://jsonapi.org/format/#fetching-pagination):
> Keys MUST either be omitted or have a null value to indicate …
> Support links with null values

- jsonapi/data_structs.go
- jsonapi/fixtures_test.go
- jsonapi/marshal.go
- jsonapi/marshal_test.go
As per the [jsonapi](http://jsonapi.org/format/#document-resource-objects) Resource Objects should be able to have "meta" member pointing to a "Meta Object"
> Allow resources to specify meta using the new MarshalMeta interface

- api.go
- jsonapi/fixtures_test.go
- jsonapi/unmarshal.go
- jsonapi/unmarshal_test.go
This PR fixes some instances where these methods are being called but their errors are not being checked. Also adds a test in the jsonapi library for this behavior and fixes the behavior of a fixture that used to return an error that was ignored.
> Add missing error checks to SetToOneReferenceID and SetToManyReferenceIDs calls

- jsonapi/fixtures_test.go
- jsonapi/unmarshal.go
- jsonapi/unmarshal_test.go
We noticed that the meta field was supported on the marshal side of things on the resource level, but was missing on the unmarshal side.
This PR adds a new interface:
```
type UnmarshalResourceMeta interface {
MarshalIdentifier
SetResourceMeta(json.RawMessage) error
}
```
The `UnmarshalResourceMeta` allows you to unmarshal the meta field when it's included on the resource object
Let me know what you think
> Adding initial support for the meta field inside of data containers
